export const apiResponse = {
    "header": {
        "statut": 200,
        "message": "OK",
        "total": 3,
        "debut": 0,
        "nombre": 3
    },
    "etablissements": [
        {
            "siren": "752793109",
            "nic": "00030",
            "siret": "75279310900030",
            "statutDiffusionEtablissement": "O",
            "dateCreationEtablissement": "2022-09-01",
            "trancheEffectifsEtablissement": null,
            "anneeEffectifsEtablissement": null,
            "activitePrincipaleRegistreMetiersEtablissement": null,
            "dateDernierTraitementEtablissement": "2022-10-25T09:44:06",
            "etablissementSiege": false,
            "nombrePeriodesEtablissement": 1,
            "uniteLegale": {
                "etatAdministratifUniteLegale": "A",
                "statutDiffusionUniteLegale": "O",
                "dateCreationUniteLegale": "2012-07-12",
                "categorieJuridiqueUniteLegale": "5710",
                "denominationUniteLegale": "KIPSOFT",
                "sigleUniteLegale": null,
                "denominationUsuelle1UniteLegale": null,
                "denominationUsuelle2UniteLegale": null,
                "denominationUsuelle3UniteLegale": null,
                "sexeUniteLegale": null,
                "nomUniteLegale": null,
                "nomUsageUniteLegale": null,
                "prenom1UniteLegale": null,
                "prenom2UniteLegale": null,
                "prenom3UniteLegale": null,
                "prenom4UniteLegale": null,
                "prenomUsuelUniteLegale": null,
                "pseudonymeUniteLegale": null,
                "activitePrincipaleUniteLegale": "62.02A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "identifiantAssociationUniteLegale": null,
                "economieSocialeSolidaireUniteLegale": "N",
                "societeMissionUniteLegale": "N",
                "caractereEmployeurUniteLegale": "O",
                "trancheEffectifsUniteLegale": "03",
                "anneeEffectifsUniteLegale": "2020",
                "nicSiegeUniteLegale": "00014",
                "dateDernierTraitementUniteLegale": "2022-10-25T09:44:06",
                "categorieEntreprise": "PME",
                "anneeCategorieEntreprise": "2020"
            },
            "adresseEtablissement": {
                "complementAdresseEtablissement": "IMMEUBLE ACTYS 1",
                "numeroVoieEtablissement": "55",
                "indiceRepetitionEtablissement": null,
                "typeVoieEtablissement": null,
                "libelleVoieEtablissement": "L'OCCITANE",
                "codePostalEtablissement": "31670",
                "libelleCommuneEtablissement": "LABEGE",
                "libelleCommuneEtrangerEtablissement": null,
                "distributionSpecialeEtablissement": null,
                "codeCommuneEtablissement": "31254",
                "codeCedexEtablissement": null,
                "libelleCedexEtablissement": null,
                "codePaysEtrangerEtablissement": null,
                "libellePaysEtrangerEtablissement": null
            },
            "adresse2Etablissement": {
                "complementAdresse2Etablissement": null,
                "numeroVoie2Etablissement": null,
                "indiceRepetition2Etablissement": null,
                "typeVoie2Etablissement": null,
                "libelleVoie2Etablissement": null,
                "codePostal2Etablissement": null,
                "libelleCommune2Etablissement": null,
                "libelleCommuneEtranger2Etablissement": null,
                "distributionSpeciale2Etablissement": null,
                "codeCommune2Etablissement": null,
                "codeCedex2Etablissement": null,
                "libelleCedex2Etablissement": null,
                "codePaysEtranger2Etablissement": null,
                "libellePaysEtranger2Etablissement": null
            },
            "periodesEtablissement": [
                {
                    "dateFin": null,
                    "dateDebut": "2022-09-01",
                    "etatAdministratifEtablissement": "A",
                    "changementEtatAdministratifEtablissement": false,
                    "enseigne1Etablissement": null,
                    "enseigne2Etablissement": null,
                    "enseigne3Etablissement": null,
                    "changementEnseigneEtablissement": false,
                    "denominationUsuelleEtablissement": null,
                    "changementDenominationUsuelleEtablissement": false,
                    "activitePrincipaleEtablissement": "62.02A",
                    "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                    "changementActivitePrincipaleEtablissement": false,
                    "caractereEmployeurEtablissement": "N",
                    "changementCaractereEmployeurEtablissement": false
                }
            ]
        },
        {
            "siren": "752793109",
            "nic": "00022",
            "siret": "75279310900022",
            "statutDiffusionEtablissement": "O",
            "dateCreationEtablissement": "2020-02-24",
            "trancheEffectifsEtablissement": null,
            "anneeEffectifsEtablissement": null,
            "activitePrincipaleRegistreMetiersEtablissement": null,
            "dateDernierTraitementEtablissement": "2022-10-25T09:44:06",
            "etablissementSiege": false,
            "nombrePeriodesEtablissement": 2,
            "uniteLegale": {
                "etatAdministratifUniteLegale": "A",
                "statutDiffusionUniteLegale": "O",
                "dateCreationUniteLegale": "2012-07-12",
                "categorieJuridiqueUniteLegale": "5710",
                "denominationUniteLegale": "KIPSOFT",
                "sigleUniteLegale": null,
                "denominationUsuelle1UniteLegale": null,
                "denominationUsuelle2UniteLegale": null,
                "denominationUsuelle3UniteLegale": null,
                "sexeUniteLegale": null,
                "nomUniteLegale": null,
                "nomUsageUniteLegale": null,
                "prenom1UniteLegale": null,
                "prenom2UniteLegale": null,
                "prenom3UniteLegale": null,
                "prenom4UniteLegale": null,
                "prenomUsuelUniteLegale": null,
                "pseudonymeUniteLegale": null,
                "activitePrincipaleUniteLegale": "62.02A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "identifiantAssociationUniteLegale": null,
                "economieSocialeSolidaireUniteLegale": "N",
                "societeMissionUniteLegale": "N",
                "caractereEmployeurUniteLegale": "O",
                "trancheEffectifsUniteLegale": "03",
                "anneeEffectifsUniteLegale": "2020",
                "nicSiegeUniteLegale": "00014",
                "dateDernierTraitementUniteLegale": "2022-10-25T09:44:06",
                "categorieEntreprise": "PME",
                "anneeCategorieEntreprise": "2020"
            },
            "adresseEtablissement": {
                "complementAdresseEtablissement": null,
                "numeroVoieEtablissement": "1149",
                "indiceRepetitionEtablissement": null,
                "typeVoieEtablissement": null,
                "libelleVoieEtablissement": "LA PYRENEENNE",
                "codePostalEtablissement": "31670",
                "libelleCommuneEtablissement": "LABEGE",
                "libelleCommuneEtrangerEtablissement": null,
                "distributionSpecialeEtablissement": null,
                "codeCommuneEtablissement": "31254",
                "codeCedexEtablissement": null,
                "libelleCedexEtablissement": null,
                "codePaysEtrangerEtablissement": null,
                "libellePaysEtrangerEtablissement": null
            },
            "adresse2Etablissement": {
                "complementAdresse2Etablissement": null,
                "numeroVoie2Etablissement": null,
                "indiceRepetition2Etablissement": null,
                "typeVoie2Etablissement": null,
                "libelleVoie2Etablissement": null,
                "codePostal2Etablissement": null,
                "libelleCommune2Etablissement": null,
                "libelleCommuneEtranger2Etablissement": null,
                "distributionSpeciale2Etablissement": null,
                "codeCommune2Etablissement": null,
                "codeCedex2Etablissement": null,
                "libelleCedex2Etablissement": null,
                "codePaysEtranger2Etablissement": null,
                "libellePaysEtranger2Etablissement": null
            },
            "periodesEtablissement": [
                {
                    "dateFin": null,
                    "dateDebut": "2022-09-01",
                    "etatAdministratifEtablissement": "F",
                    "changementEtatAdministratifEtablissement": true,
                    "enseigne1Etablissement": null,
                    "enseigne2Etablissement": null,
                    "enseigne3Etablissement": null,
                    "changementEnseigneEtablissement": false,
                    "denominationUsuelleEtablissement": null,
                    "changementDenominationUsuelleEtablissement": false,
                    "activitePrincipaleEtablissement": "62.02A",
                    "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                    "changementActivitePrincipaleEtablissement": false,
                    "caractereEmployeurEtablissement": "O",
                    "changementCaractereEmployeurEtablissement": false
                },
                {
                    "dateFin": "2022-08-31",
                    "dateDebut": "2020-02-24",
                    "etatAdministratifEtablissement": "A",
                    "changementEtatAdministratifEtablissement": false,
                    "enseigne1Etablissement": null,
                    "enseigne2Etablissement": null,
                    "enseigne3Etablissement": null,
                    "changementEnseigneEtablissement": false,
                    "denominationUsuelleEtablissement": null,
                    "changementDenominationUsuelleEtablissement": false,
                    "activitePrincipaleEtablissement": "62.02A",
                    "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                    "changementActivitePrincipaleEtablissement": false,
                    "caractereEmployeurEtablissement": "O",
                    "changementCaractereEmployeurEtablissement": false
                }
            ]
        },
        {
            "siren": "752793109",
            "nic": "00014",
            "siret": "75279310900014",
            "statutDiffusionEtablissement": "O",
            "dateCreationEtablissement": "2012-07-12",
            "trancheEffectifsEtablissement": "03",
            "anneeEffectifsEtablissement": "2020",
            "activitePrincipaleRegistreMetiersEtablissement": null,
            "dateDernierTraitementEtablissement": "2022-08-29T09:42:58",
            "etablissementSiege": true,
            "nombrePeriodesEtablissement": 2,
            "uniteLegale": {
                "etatAdministratifUniteLegale": "A",
                "statutDiffusionUniteLegale": "O",
                "dateCreationUniteLegale": "2012-07-12",
                "categorieJuridiqueUniteLegale": "5710",
                "denominationUniteLegale": "KIPSOFT",
                "sigleUniteLegale": null,
                "denominationUsuelle1UniteLegale": null,
                "denominationUsuelle2UniteLegale": null,
                "denominationUsuelle3UniteLegale": null,
                "sexeUniteLegale": null,
                "nomUniteLegale": null,
                "nomUsageUniteLegale": null,
                "prenom1UniteLegale": null,
                "prenom2UniteLegale": null,
                "prenom3UniteLegale": null,
                "prenom4UniteLegale": null,
                "prenomUsuelUniteLegale": null,
                "pseudonymeUniteLegale": null,
                "activitePrincipaleUniteLegale": "62.02A",
                "nomenclatureActivitePrincipaleUniteLegale": "NAFRev2",
                "identifiantAssociationUniteLegale": null,
                "economieSocialeSolidaireUniteLegale": "N",
                "societeMissionUniteLegale": "N",
                "caractereEmployeurUniteLegale": "O",
                "trancheEffectifsUniteLegale": "03",
                "anneeEffectifsUniteLegale": "2020",
                "nicSiegeUniteLegale": "00014",
                "dateDernierTraitementUniteLegale": "2022-10-25T09:44:06",
                "categorieEntreprise": "PME",
                "anneeCategorieEntreprise": "2020"
            },
            "adresseEtablissement": {
                "complementAdresseEtablissement": null,
                "numeroVoieEtablissement": "1254",
                "indiceRepetitionEtablissement": null,
                "typeVoieEtablissement": "RUE",
                "libelleVoieEtablissement": "DE LA CROIX BLANCHE",
                "codePostalEtablissement": "46130",
                "libelleCommuneEtablissement": "SAINT-MICHEL-LOUBEJOU",
                "libelleCommuneEtrangerEtablissement": null,
                "distributionSpecialeEtablissement": null,
                "codeCommuneEtablissement": "46284",
                "codeCedexEtablissement": null,
                "libelleCedexEtablissement": null,
                "codePaysEtrangerEtablissement": null,
                "libellePaysEtrangerEtablissement": null
            },
            "adresse2Etablissement": {
                "complementAdresse2Etablissement": null,
                "numeroVoie2Etablissement": null,
                "indiceRepetition2Etablissement": null,
                "typeVoie2Etablissement": null,
                "libelleVoie2Etablissement": null,
                "codePostal2Etablissement": null,
                "libelleCommune2Etablissement": null,
                "libelleCommuneEtranger2Etablissement": null,
                "distributionSpeciale2Etablissement": null,
                "codeCommune2Etablissement": null,
                "codeCedex2Etablissement": null,
                "libelleCedex2Etablissement": null,
                "codePaysEtranger2Etablissement": null,
                "libellePaysEtranger2Etablissement": null
            },
            "periodesEtablissement": [
                {
                    "dateFin": null,
                    "dateDebut": "2013-01-20",
                    "etatAdministratifEtablissement": "A",
                    "changementEtatAdministratifEtablissement": false,
                    "enseigne1Etablissement": null,
                    "enseigne2Etablissement": null,
                    "enseigne3Etablissement": null,
                    "changementEnseigneEtablissement": false,
                    "denominationUsuelleEtablissement": null,
                    "changementDenominationUsuelleEtablissement": false,
                    "activitePrincipaleEtablissement": "62.02A",
                    "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                    "changementActivitePrincipaleEtablissement": false,
                    "caractereEmployeurEtablissement": "O",
                    "changementCaractereEmployeurEtablissement": true
                },
                {
                    "dateFin": "2013-01-19",
                    "dateDebut": "2012-07-12",
                    "etatAdministratifEtablissement": "A",
                    "changementEtatAdministratifEtablissement": false,
                    "enseigne1Etablissement": null,
                    "enseigne2Etablissement": null,
                    "enseigne3Etablissement": null,
                    "changementEnseigneEtablissement": false,
                    "denominationUsuelleEtablissement": null,
                    "changementDenominationUsuelleEtablissement": false,
                    "activitePrincipaleEtablissement": "62.02A",
                    "nomenclatureActivitePrincipaleEtablissement": "NAFRev2",
                    "changementActivitePrincipaleEtablissement": false,
                    "caractereEmployeurEtablissement": "N",
                    "changementCaractereEmployeurEtablissement": false
                }
            ]
        }
    ]
};